### PR TITLE
💅 Improvments

### PR DESCRIPTION
**Pull request by Hacksore**
i made some things better but i still cant use it, tell me how.

### CODE REVIEW

**Comment by Hacksore** [comment]
So i can get it working from curl but attempts in the browser fail.

image

**Comment by Hacksore** [comment]
My working theory is that we need TLS termination past caddy because caddy is not doing the request to our dest for us to handle TLS termination.

image

**Comment by Hacksore** [comment]
Interesting if i just bypass caddy this will still work.

```
hacksore@eloy:/tmp/vite-project
 $ curl -vvv -H "Origin: https://google.com/test" http://localhost:6969
*   Trying [::1]:6969...
* Connected to localhost (::1) port 6969
> GET / HTTP/1.1
> Host: localhost:6969
> User-Agent: curl/8.4.0
> Accept: */*
> Origin: https://google.com/test
>
< HTTP/1.1 404 Not Found
< content-type: text/html; charset=UTF-8
< referrer-policy: no-referrer
< content-length: 64
< date: Sat, 06 Apr 2024 14:15:39 GMT
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< connection: close
<
* Closing connection
<html lang=en>look we can do things to patch content 🥳</html>%     
```

**Comment by nickhudkins** [comment]
Turns out I was being dumb and none of what I had done quite handled what I wanted. I actually needed a proxy server, not just a thing acting like a reverse proxy. So... mainline now works gooder as a proxy, handles HTTPS, now we need a new approach to this portion. Still should do a `pac` file, and I'd rather not expose `mockttp` types / payloads, they're gross. To be honest, I sort of really dislike `mockttp`, as I want just like `http/https` native `{Incoming|Outgoing}Message` types to work with.

**Pull request closed without merging**
